development:
  adapter: postgresql
  encoding: unicode
  database: creditPlansProduction
  pool: 5
  username: ubuntu
  password: password1
  host: cloudtaller2.cplwnx1lhyeo.us-west-2.rds.amazonaws.com
  
production:
  adapter: postgresql
  encoding: unicode
  database: creditPlansProduction
  pool: 10
  username: ubuntu
  password: password1
  host: cloudtaller2.cplwnx1lhyeo.us-west-2.rds.amazonaws.com
  # port: 5432
  # socket: /tmp/postgresql.sock
